import { restoreI_Players } from './server/firestoreFunctions';

export const players = [
    { rank: 6, name: "Ludvig Aberg" },
    { rank: 11, name: "Byeong Hun An" },
    { rank: 0, name: "Abraham Ancer" },
    { rank: 0, name: "Mason Andersen" },
    { rank: 22, name: "Christiaan Bezuidenhout" },
    { rank: 12, name: "Akshay Bhatia" },
    { rank: 161, name: "Alexander Björk" },
    { rank: 0, name: "Denwit David Boriboonsub" },
    { rank: 0, name: "Dan Bradbury" },
    { rank: 39, name: "Keegan Bradley" },
    { rank: 0, name: "Daniel Brown" },
    { rank: 0, name: "Dean Burmester" },
    { rank: 31, name: "Sam Burns" },
    { rank: 128, name: "Jorge Campillo" },
    { rank: 0, name: "Laurie Canter" },
    { rank: 9, name: "Patrick Cantlay" },
    { rank: 0, name: "John Catlin" },
    { rank: 0, name: "Alex Cejka" },
    { rank: 169, name: "Stewart Cink" },
    { rank: 5, name: "Wyndham Clark" },
    { rank: 0, name: "Darren Clarke" },
    { rank: 0, name: "Dominic Clemons" },
    { rank: 54, name: "Eric Cole" },
    { rank: 30, name: "Corey Conners" },
    { rank: 0, name: "Sean Crocker" },
    { rank: 0, name: "John Daly" },
    { rank: 26, name: "Jason Day" },
    { rank: 0, name: "Santiago de la Fuente" },
    { rank: 0, name: "Joseph Dean" },
    { rank: 0, name: "Bryson DeChambeau" },
    { rank: 0, name: "Matthew Dodd-Berry" },
    { rank: 44, name: "Austin Eckroat" },
    { rank: 0, name: "Ernie Els" },
    { rank: 0, name: "Nacho Elvira" },
    { rank: 45, name: "Harris English" },
    { rank: 0, name: "Ewen Ferguson" },
    { rank: 0, name: "Darren Fichardt" },
    { rank: 14, name: "Tony Finau" },
    { rank: 37, name: "Matt Fitzpatrick" },
    { rank: 25, name: "Tommy Fleetwood" },
    { rank: 98, name: "Rickie Fowler" },
    { rank: 109, name: "Ryan Fox" },
    { rank: 70, name: "Lucas Glover" },
    { rank: 58, name: "Ben Griffin" },
    { rank: 67, name: "Emiliano Grillo" },
    { rank: 34, name: "Adam Hadwin" },
    { rank: 0, name: "Todd Hamilton" },
    { rank: 20, name: "Brian Harman" },
    { rank: 222, name: "Padraig Harrington" },
    { rank: 91, name: "Tyrrell Hatton" },
    { rank: 0, name: "Mike Hendry" },
    { rank: 21, name: "Russell Henley" },
    { rank: 0, name: "Angel Hidalgo Portillo" },
    { rank: 0, name: "Daniel Hillier" },
    { rank: 99, name: "Ryo Hisatsune" },
    { rank: 19, name: "Tom Hoge" },
    { rank: 75, name: "Nicolai Højgaard" },
    { rank: 0, name: "Rasmus Højgaard" },
    { rank: 32, name: "Max Homa" },
    { rank: 47, name: "Billy Horschel" },
    { rank: 0, name: "Sam Horsfield" },
    { rank: 0, name: "Rikuya Hoshino" },
    { rank: 51, name: "Viktor Hovland" },
    { rank: 53, name: "Mackenzie Hughes" },
    { rank: 0, name: "Sam Hutsby" },
    { rank: 10, name: "Sungjae Im" },
    { rank: 0, name: "Aguri Iwasaki" },
    { rank: 27, name: "Stephan Jaeger" },
    { rank: 0, name: "Dustin Johnson" },
    { rank: 145, name: "Zach Johnson" },
    { rank: 0, name: "Matthew Jordan" },
    { rank: 0, name: "Yuto Katsuragawa" },
    { rank: 0, name: "Masahiro Kawamura" },
    { rank: 0, name: "Minkyu Kim" },
    { rank: 35, name: "Si Woo Kim" },
    { rank: 38, name: "Tom Kim" },
    { rank: 0, name: "Ryosuke Kinoshita" },
    { rank: 24, name: "Chris Kirk" },
    { rank: 79, name: "Kurt Kitayama" },
    { rank: 0, name: "Kazuma Kobori" },
    { rank: 0, name: "Brooks Koepka" },
    { rank: 0, name: "Guntaek Koh" },
    { rank: 0, name: "Romain Langasque" },
    { rank: 0, name: "Thriston Lawrence" },
    { rank: 59, name: "Min Woo Lee" },
    { rank: 0, name: "Justin Leonard" },
    { rank: 0, name: "Charlie Lindh" },
    { rank: 13, name: "Shane Lowry" },
    { rank: 0, name: "Joost Luiten" },
    { rank: 16, name: "Robert MacIntyre" },
    { rank: 0, name: "Matteo Manassero" },
    { rank: 0, name: "Richard Mansell" },
    { rank: 0, name: "Luis Masaveu" },
    { rank: 8, name: "Hideki Matsuyama" },
    { rank: 40, name: "Denny McCarthy" },
    { rank: 0, name: "Jack McDonald" },
    { rank: 3, name: "Rory McIlroy" },
    { rank: 0, name: "Tom McKibbin" },
    { rank: 65, name: "Maverick McNealy" },
    { rank: 0, name: "Adrian Meronk" },
    { rank: 0, name: "Phil Mickelson" },
    { rank: 0, name: "Guido Migliozzi" },
    { rank: 202, name: "Francesco Molinari" },
    { rank: 0, name: "Jaime Montojo" },
    { rank: 60, name: "Taylor Moore" },
    { rank: 4, name: "Collin Morikawa" },
    { rank: 0, name: "Tommy Morrison" },
    { rank: 0, name: "Keita Nakajima" },
    { rank: 0, name: "Joaquin Niemann" },
    { rank: 0, name: "Liam Nolan" },
    { rank: 48, name: "Alex Noren" },
    { rank: 194, name: "Vincent Norrman" },
    { rank: 0, name: "Andy Ogletree" },
    { rank: 0, name: "Jacob Skov Olesen" },
    { rank: 155, name: "Thorbjørn Olesen" },
    { rank: 0, name: "Louis Oosthuizen" },
    { rank: 85, name: "C.T. Pan" },
    { rank: 0, name: "Yannik Paul" },
    { rank: 15, name: "Matthieu Pavon" },
    { rank: 66, name: "Victor Perez" },
    { rank: 29, name: "J.T. Poston" },
    { rank: 0, name: "David Puig" },
    { rank: 0, name: "Jon Rahm" },
    { rank: 50, name: "Aaron Rai" },
    { rank: 76, name: "Justin Rose" },
    { rank: 0, name: "Gordon Sargent" },
    { rank: 2, name: "Xander Schauffele" },
    { rank: 1, name: "Scottie Scheffler" },
    { rank: 72, name: "Adam Schenk" },
    { rank: 49, name: "Adam Scott" },
    { rank: 0, name: "Calum Scott" },
    { rank: 0, name: "Shubhankar Sharma" },
    { rank: 0, name: "Marcel Siem" },
    { rank: 0, name: "Cameron Smith" },
    { rank: 0, name: "Jordan Smith" },
    { rank: 0, name: "Elvis Smylie" },
    { rank: 0, name: "Sebastian Soderberg" },
    { rank: 0, name: "Young-han Song" },
    { rank: 0, name: "Matthew Southgate" },
    { rank: 61, name: "Jordan Spieth" },
    { rank: 0, name: "Henrik Stenson" },
    { rank: 18, name: "Sepp Straka" },
    { rank: 0, name: "Jasper Stubbs" },
    { rank: 0, name: "Jesper Svensson" },
    { rank: 43, name: "Nick Taylor" },
    { rank: 7, name: "Sahith Theegala" },
    { rank: 17, name: "Justin Thomas" },
    { rank: 23, name: "Davis Thompson" },
    { rank: 64, name: "Brendon Todd" },
    { rank: 88, name: "Sami Valimaki" },
    { rank: 0, name: "Altin van der Merwe" },
    { rank: 0, name: "Ryan van Velzen" },
    { rank: 118, name: "Matt Wallace" },
    { rank: 0, name: "Jeunghun Wang" },
    { rank: 166, name: "Gary Woodland" },
    { rank: 220, name: "Tiger Woods" },
    { rank: 33, name: "Cameron Young" },
    { rank: 41, name: "Will Zalatoris" }
  ];

export const getPlayers = async () => {
    return players;
  };
  
restoreI_Players(players);

//node TheOpenChampionship.js
  